# Source: cai-redteam/charts/prefect-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prefect-server
  namespace: f5-ai-redteam
  labels:
    app.kubernetes.io/name: prefect-server
    app.kubernetes.io/instance: cai-redteam
    app.kubernetes.io/version: 3.1.12
    app.kubernetes.io/component: server
    prefect-version: 3.1.12
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
spec:
  type: ClusterIP
  ports:
  - name: server-svc-port
    port: 4200
    protocol: TCP
    targetPort: 4200
    nodePort: null
  selector:
    app.kubernetes.io/name: prefect-server
    app.kubernetes.io/instance: cai-redteam
    app.kubernetes.io/component: server
