# Source: cai-redteam/charts/prefect-worker/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-worker
  namespace: f5-ai-redteam
  labels:
    app.kubernetes.io/name: prefect-worker
    app.kubernetes.io/instance: cai-redteam
    app.kubernetes.io/version: 3.1.12
    app.kubernetes.io/component: worker
    prefect-version: 3.1.12
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
