# Source: cai-redteam/charts/prometheus-prefect-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cai-redteam-prometheus-prefect-exporter
  namespace: f5-ai-redteam
  labels:
    app.kubernetes.io/name: prometheus-prefect-exporter
    app.kubernetes.io/instance: cai-redteam
    app.kubernetes.io/version: 1.6.7
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
