apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cai-redteam
  annotations:
    config.kubernetes.io/local-config: "true"
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
resources:
  - namespace.yaml
  # Cloud Deploy/skaffold/helm and CRDs seem to be a bad combination; ensure the KubeAI CRDs are published from manifest
  # - https://raw.githubusercontent.com/kubeai-project/kubeai/refs/tags/v0.22.1/manifests/crds/kubeai.org_models.yaml
