---
extends: default

rules:
  line-length:
    max: 120
    ignore:
      - .github/workflows/infra-manager.yml
      - deployments/**/skaffold.yaml
  document-start:
    ignore:
      # Kpt/kustomize tooling routinely strips leading --- from files
      - deployments/**/*.yaml
