---
extends: default
ignore:
  # TODO(@memes): Don't like this, review later
  - deployments/**/*.yaml
rules:
  line-length:
    max: 120
    ignore:
      - .github/workflows/infra-manager*.yml
      - skaffold.yaml
