---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: f5-ai-demo-pre-requisites
  annotations:
    config.kubernetes.io/local-config: "true"
build: {}
manifests:
  kustomize:
    paths:
      - deployments/pre-requisites
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: f5-ai-demo
  annotations:
    config.kubernetes.io/local-config: "true"
build: {}
manifests:
  rawYaml:
    - deployments/shared-services/auth-proxy/*yaml
    - deployments/shared-services/gateway/*yaml
    - deployments/f5-ai/moderator/*.yaml
    - deployments/f5-ai/scanner/**/*.yaml
    - deployments/f5-ai/scanner/*.yaml
    - deployments/f5-ai/redteam/**/*.yaml
    - deployments/f5-ai/redteam/*.yaml
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command:
              - kubectl
              - delete
              - job
              - cai-workflows-bootstrap
              - --namespace
              - f5-ai-redteam
              - --ignore-not-found
      after:
        - host:
            command:
              - sh
              - -c
              - 'kubectl set env -n f5-ai-redteam deployment/prefect-worker PREFECT_KUBERNETES_CLUSTER_UID="$(kubectl get ns kube-system -o template --template "{{.metadata.uid}}")"; exit 0'
        - host:
            command:
              - sh
              - -c
              - 'kubectl create job cai-workflows-bootstrap --namespace f5-ai-redteam --from=cronjob/cai-workflows; exit 0'
