apiVersion: batch/v1
kind: Job
metadata:
  name: psql-drop-cai-dbs
  namespace: shared-services
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: pg-admin
      initContainers:
        - name: extract-pgpass
          image: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/busybox:1.37.0
          command:
            - /bin/sh
            - -c
            # yamllint disable-line rule:line-length
            - "cp /run/source/.pgpass /run/target/.pgpass && chown root:root /run/target/.pgpass && chmod 0400 /run/target/.pgpass"
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /run/target
              name: pg-creds
            - mountPath: /run/source
              name: pg-admin-pgpass
      containers:
        - name: psql
          image: pus-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/postgres:15.16-alpine
          imagePullPolicy: IfNotPresent
          command:
            - psql
            - postgresql://$(PGUSER)@$(PGHOST):5432/postgres
            - --no-password
            - --file
            - /run/psql-scripts/drop_cai_resources.sql
          env:
            - name: PGPASSFILE
              value: /run/pg-creds/.pgpass
            - name: PGHOST
              value: CHANGE_ME
            - name: PGUSER
              value: CHANGE_ME
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /run/pg-creds
              name: pg-creds
            - mountPath: /run/psql-scripts
              name: psql-scripts
      volumes:
        - name: pg-creds
          emptyDir: {}
        - name: pg-admin-pgpass
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: pg-admin-pgpass
        - name: psql-scripts
          configMap:
            name: psql-scripts
      restartPolicy: OnFailure
