# Thanks for using NGINXaaS.
# This is the default NGINX config that will work on any NGINXaaS deployment. Use this as a starting
# point to get your NGINXaaS deployment going, and come back to edit later to fit your needs.

http {
    # The common upstream
    upstream gw {
        server 172.16.0.5;
    }

    include /etc/nginx/conf.d/*.conf;

    # It is recommended to not modify these log file paths.
    # If log exporting is configured, NGINXaaS only scrapes
    # logs in /var/log/nginx/
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log error;
}

## Note: the following settings are necessary for NGINXaaS to function properly.
## Editing these will have no effect as changes will be silently overridden.
## See https://docs.nginx.com/nginxaas/google/getting-started/nginx-configuration/overview/#directives-that-cannot-be-overridden
user nginx;
pid /run/nginx/nginx.pid;
worker_processes auto;
worker_rlimit_nofile 524288;
events {
	worker_connections 150000;
}
