# Source: body-based-routing/templates/gke.yaml
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: bbr-healthcheck
  namespace: shared-services
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: GRPC
      grpcHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 9005
  targetRef:
    group: ""
    kind: Service
    name: body-based-router
    namespace: shared-services
