# Source: body-based-routing/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: body-based-router-shared-services
  namespace: shared-services
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
