# Source: body-based-routing/templates/bbr.yaml
apiVersion: v1
kind: Service
metadata:
  name: body-based-router
  namespace: shared-services
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
spec:
  selector:
    app: body-based-router
  ports:
  - protocol: TCP
    port: 9004
    targetPort: 9004
    appProtocol: HTTP2
  type: ClusterIP
