# NOTE: This will be populated by secret-sync-generator pipeline component.
# NOTE: This will be populated by secret-sync-generator pipeline component.
# NOTE: This will be populated by secret-sync-generator pipeline component.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cai-moderator-auth
  namespace: f5-ai-moderator
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
spec:
  provider: gke
  parameters:
    secrets: | # NOTE: This will be populated by secret-sync-generator pipeline component.
      - extractJSONKey: CAI_MODERATOR_AUTH_ADMIN_PASSWORD
        path: .CAI_MODERATOR_AUTH_ADMIN_PASSWORD
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_AUTH_IDP_CLIENT_ID
        path: .CAI_MODERATOR_AUTH_IDP_CLIENT_ID
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_AUTH_IDP_CLIENT_SECRET
        path: .CAI_MODERATOR_AUTH_IDP_CLIENT_SECRET
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_AUTH_IDP_ISSUER
        path: .CAI_MODERATOR_AUTH_IDP_ISSUER
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_DB_ADMIN_PASSWORD
        path: .CAI_MODERATOR_DB_ADMIN_PASSWORD
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_DB_MODERATOR_PASSWORD
        path: .CAI_MODERATOR_DB_MODERATOR_PASSWORD
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_DEFAULT_LICENSE
        path: .CAI_MODERATOR_DEFAULT_LICENSE
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_EMAIL_PASSWORD
        path: .CAI_MODERATOR_EMAIL_PASSWORD
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_EMAIL_USER
        path: .CAI_MODERATOR_EMAIL_USER
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_ENCRYPTION_KEY
        path: .CAI_MODERATOR_ENCRYPTION_KEY
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
      - extractJSONKey: CAI_MODERATOR_JOB_MANAGER_ENCRYPTION_KEY
        path: .CAI_MODERATOR_JOB_MANAGER_ENCRYPTION_KEY
        resourceName: projects/f5-gcs-4138-sales-cloudnext25/secrets/f5-ai-demo-us-ce1-cai-moderator-auth/versions/latest
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: cai-moderator-auth
  namespace: f5-ai-moderator
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
spec:
  serviceAccountName: cai-moderator-sa
  secretProviderClassName: cai-moderator-auth
  secretObject:
    type: Opaque
    data:
    - sourcePath: .CAI_MODERATOR_AUTH_ADMIN_PASSWORD
      targetKey: CAI_MODERATOR_AUTH_ADMIN_PASSWORD
    - sourcePath: .CAI_MODERATOR_AUTH_IDP_CLIENT_ID
      targetKey: CAI_MODERATOR_AUTH_IDP_CLIENT_ID
    - sourcePath: .CAI_MODERATOR_AUTH_IDP_CLIENT_SECRET
      targetKey: CAI_MODERATOR_AUTH_IDP_CLIENT_SECRET
    - sourcePath: .CAI_MODERATOR_AUTH_IDP_ISSUER
      targetKey: CAI_MODERATOR_AUTH_IDP_ISSUER
    - sourcePath: .CAI_MODERATOR_DB_ADMIN_PASSWORD
      targetKey: CAI_MODERATOR_DB_ADMIN_PASSWORD
    - sourcePath: .CAI_MODERATOR_DB_MODERATOR_PASSWORD
      targetKey: CAI_MODERATOR_DB_MODERATOR_PASSWORD
    - sourcePath: .CAI_MODERATOR_DEFAULT_LICENSE
      targetKey: CAI_MODERATOR_DEFAULT_LICENSE
    - sourcePath: .CAI_MODERATOR_EMAIL_PASSWORD
      targetKey: CAI_MODERATOR_EMAIL_PASSWORD
    - sourcePath: .CAI_MODERATOR_EMAIL_USER
      targetKey: CAI_MODERATOR_EMAIL_USER
    - sourcePath: .CAI_MODERATOR_ENCRYPTION_KEY
      targetKey: CAI_MODERATOR_ENCRYPTION_KEY
    - sourcePath: .CAI_MODERATOR_JOB_MANAGER_ENCRYPTION_KEY
      targetKey: CAI_MODERATOR_JOB_MANAGER_ENCRYPTION_KEY
