apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-admin
  namespace: shared-services
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pg-admin-pgpass
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "replace-me" # from-param: foo
        path: ".pgpass"
        extractJSONKey: pgpass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-scripts
  namespace: shared-services
  annotations:
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
data:
  drop_cai_resources.sql: |-
    DROP DATABASE IF EXISTS keycloak;
    DROP DATABASE IF EXISTS moderator;
    DROP DATABASE IF EXISTS moderator_metrics;
    DROP DATABASE IF EXISTS prefect;
    DROP USER IF EXISTS keycloak;
    DROP USER IF EXISTS moderator;
    DROP USER IF EXISTS prefect;
