apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: shared-services
  annotations:
    config.kubernetes.io/local-config: "true"
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
build: {}
manifests:
  kustomize:
    paths:
      - ./
deploy:
  kubectl: {}
