apiVersion: fn.kpt.dev/v1alpha1
kind: SetAnnotations
metadata:
  name: default
  annotations:
    config.kubernetes.io/local-config: "true"
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
annotations:
  community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
  community.f5.com/email: m.emes@f5.com
  community.f5.com/owner: emes
# additionalAnnotationFields:
#   - kind: Config
#     group: skaffold
#     create: true
#     path: manifests/helm/releases/setValues/models/cai-phi-4-gptq-4bit/annotations
#   - kind: Config
#     group: skaffold
#     create: true
#     path: manifests/helm/releases/setValues/kubeAI/serviceAccount/annotations
#   - kind: Config
#     group: skaffold
#     create: true
#     path: manifests/helm/releases/setValues/kubeAI/modelServiceAccount/annotations
#   - kind: Config
#     group: skaffold
#     create: true
#     path: manifests/helm/releases/setValues/kubeAI/podAnnotations
#   - kind: Config
#     group: skaffold
#     create: true
#     path: manifests/helm/releases/setValues/kubeAI/serviceAnnotations
