apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: f5-ai-cai-redteam
  annotations:
    config.kubernetes.io/local-config: "true"
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
build: {}
manifests:
  kustomize:
    paths:
      - manifests
deploy:
  kubectl: {}
  helm:
    releases:
      - name: cai-redteam
        remoteChart: oci://us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/harbor.calypsoai.app/calypsoai/cai-redteam
        version: 1.14.6
        namespace: cai-redteam
        createNamespace: true
        setValues:
          prefect-server:
            server:
              image:
                repository: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/prefecthq/prefect
              # The next three entries will need to be modified if this package is deployed to namespace other than the
              # default of cai-redteam.
              prefectApiUrl: http://prefect-server.cai-redteam.svc.cluster.local:4200/api
          prefect-worker:
            worker:
              serverApiConfig:
                apiUrl: http://prefect-server.cai-redteam.svc.cluster.local:4200/api
              image:
                repository: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/prefecthq/prefect
          cai-workflows:
            env:
              PREFECT_API_URL: http://prefect-server.cai-redteam.svc.cluster.local:4200/api
              # If the cai-moderator package is deployed to a namespace other than the default of cai-moderator the next
              # line will need to change to match.
              CAI_WORKFLOWS_WEBHOOK_URL: http://cai-moderator.cai-moderator.svc.cluster.local:5500/internal/hooks/attack-events
            image:
              repository: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/harbor.calypsoai.app/calypsoai/cai_workflows
            # NOTE: An imagePullSecret is not needed when pulling from a private GAR repo with access managed through
            # IAM. Remove if relying on regcreds from upstream chart.
            imagePullSecrets: []
          models:
            cai-mistral-nemo-instruct-2407:
              env:
                LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nvidia/lib64
              image: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/harbor.calypsoai.app/calypsoai/cai-redteam-worker:v1.0.7
              resourceProfile: nvidia-gpu-a100-40gb:1  # kpt-set: ${cai-redteam-model-resource-profile}
          kubeai:
            crds:
              # NOTE: CRD is being installed in a dependency
              enabled: false
            # NOTE: An imagePullSecret is not needed when pulling from a private GAR repo with access managed through
            # IAM. Remove if relying on regcreds from upstream chart.
            imagePullSecrets: []
            image:
              repository: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/harbor.calypsoai.app/calypsoai/kubeai
            modelLoading:
              image: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/harbor.calypsoai.app/calypsoai/kubeai-model-loader:v0.14.0
            # The values below are not directly exposed in upstream cai-scanner, but are in the included kubeai
            # sub-chart and need to be changed if using a private registry.
            modelServers:
              VLLM:
                images:
                  default: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/vllm/vllm-openai:v0.10.2
                  nvidia-gpu: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/vllm/vllm-openai:v0.10.2
                  google-tpu: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/vllm-tpu:23194d83e8f2a6783b0d8c275f5f8a22faab9aec
                  gh200: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/vllm/vllm-openai:v0.10.2
            # Pull in the GKE resource profiles from sub-chart file kubeai/values-gke.yaml so that GKE ready profiles
            # are available for model selection above.
            # NOTE: The spot allocation strategy IS enabled by default for cai-redteam profiles because the nodes can be
            # provisioned on-demand and do not need to be long-lived.
            # https://docs.cloud\.google\.com/kubernetes-engine/docs/concepts/spot-vms#overview
            resourceProfiles:
              nvidia-gpu-l4:
                nodeSelector:
                  cloud\.google\.com/gke-accelerator: "nvidia-l4"
                  cloud\.google\.com/gke-spot: "true"
              nvidia-gpu-h100:
                nodeSelector:
                  cloud\.google\.com/gke-accelerator: "nvidia-h100-80gb"
                  cloud\.google\.com/gke-spot: "true"
              nvidia-gpu-a100-80gb:
                nodeSelector:
                  cloud\.google\.com/gke-accelerator: "nvidia-a100-80gb"
                  cloud\.google\.com/gke-spot: "true"
              nvidia-gpu-a100-40gb:
                nodeSelector:
                  cloud\.google\.com/gke-accelerator: "nvidia-tesla-a100"
                  cloud\.google\.com/gke-spot: "true"
              google-tpu-v5e-1x1:
                imageName: google-tpu
                limits:
                  google\.com/tpu: 1
                nodeSelector:
                  cloud\.google\.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                  cloud\.google\.com/gke-tpu-topology: "1x1"
                  cloud\.google\.com/gke-spot: "true"
              google-tpu-v5e-2x2:
                imageName: google-tpu
                limits:
                  google\.com/tpu: 1
                nodeSelector:
                  cloud\.google\.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                  cloud\.google\.com/gke-tpu-topology: "2x2"
                  cloud\.google\.com/gke-spot: "true"
              google-tpu-v5e-2x4:
                imageName: google-tpu
                limits:
                  google\.com/tpu: 1
                nodeSelector:
                  cloud\.google\.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                  cloud\.google\.com/gke-tpu-topology: "2x4"
                  cloud\.google\.com/gke-spot: "true"
            cacheProfiles:
              standard-filestore:
                sharedFilesystem:
                  storageClassName: "standard-rwx"
              premium-filestore:
                sharedFilesystem:
                  storageClassName: "premium-rwx"
          # The values below are not directly exposed in upstream cai-redteam, but are in the included
          # prometheus-prefect-exporter sub-chart and need to be changed if using a private registry and enabled.
          prometheus-prefect-exporter:
            image:
              repository: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/prefecthq/prometheus-prefect-exporter
            prefectApiUrl: http://prefect-server.cai-redteam.svc.cluster.local:4200/api
        setValueTemplates:
          prefect:
            server:
              secrets:
                connection-string: postgresql+asyncpg://prefect:prefect@{{ .DB_HOST }}:5432/prefect  # kpt-set: ${cai-redteam-prefect-db-connection-string}
