apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: f5-ai-cai-moderator
  annotations:
    config.kubernetes.io/local-config: "true"
    community.f5.com/demo-source: https://github.com/memes/f5-ai-solutions-for-google-cloud
    community.f5.com/email: m.emes@f5.com
    community.f5.com/owner: emes
build: {}
manifests:
  kustomize:
    paths:
      - manifests
deploy:
  kubectl: {}
  helm:
    releases:
      - name: cai-moderator
        remoteChart: oci://us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/harbor.calypsoai.app/calypsoai/cai-moderator
        version: 1.4.13
        namespace: cai-moderator
        createNamespace: true
        setValues:
          image:
            repository: us-docker.pkg.dev/f5-gcs-4138-sales-cloudnext25/ai-demo-oci/harbor.calypsoai.app/calypsoai/cai_moderator
          imagePullSecrets: []
          nodeSelector:
            # NOTE: These selectors ensure the cai-moderator pods get a dedicated C4 node each. Change as needed.
            cloud\.google\.com/machine-family: c4
            cloud\.google\.com/compute-class: Performance
          env:
            # The next entry will need to be modified if cai-scanner service is using a different namespace than the
            # default of cai-scanner.
            CAI_MODERATOR_SCANNER_SERVER_URL: http://cai-scanner.cai-scanner.svc.cluster.local/openai/v1
            # If this package is deployed to a namespace other than the default of cai-moderator the next line will need
            # to change to match.
            JAVA_OPTS_APPEND: -Djgroups.dns.query=cai-moderator-headless.cai-moderator.svc.cluster.local
            #
            # The following entries are dependent on values/secrets created by IaC pipelines, and change with each fresh
            # deployment, and are marked with setters to facilitate updating in an automated pipeline.
            CAI_MODERATOR_BASE_URL: https://f5-ai.strangelambda.com  # kpt-set: ${cai-moderator-console-base-url}
        setValueTemplates:
          env:
            CAI_MODERATOR_DB_ADMIN_USERNAME: '{{ .DB_ADMIN_USER }}'  # kpt-set: ${cai-moderator-db-admin-username}
            CAI_MODERATOR_DB_HOST: '{{ .DB_HOST }}'  # kpt-set: ${cai-moderator-db-host}
          secrets:
            CAI_MODERATOR_DB_ADMIN_PASSWORD: '{{ .DB_ADMIN_PASSWORD }}'  # kpt-set: ${cai-moderator-db-admin-password}
            CAI_MODERATOR_DEFAULT_LICENSE: '{{ .F5_AI_LICENSE }}'  # kpt-set: ${cai-moderator-license-token}
