# Declares an action that triggers Google Cloud Infrastructure Manager tasks on changes in the foundations/ directory.
# The intent is to trigger a Terraform plan on PR creation and changes, and an apply on merge to main.
#
# yamllint disable rule:line-length
---
name: 'Infra Manager: Foundations'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      action:
        description: Infrastructure Manager action to trigger
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - delete
          - output
  pull_request:
    paths:
      - 'foundations/**'
      - ./.github/workflows/infra-manager-foundations.yml
      - ./.github/workflows/infra-manager-wrapper.sh
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - 'foundations/**'
      - ./.github/workflows/infra-manager-foundations.yml
      - ./.github/workflows/infra-manager-wrapper.sh

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  TFPLANDOC_VERSION: 0.4.1
  # These values define the properties used by Infrastructure Manager
  DEPLOYMENT_ID: f5-ai-demo
  DEPLOYMENT_PROJECT_ID: ${{ vars.PROJECT_ID }}
  DEPLOYMENT_REGION: us-central1
  DEPLOYMENT_TF_VERSION: "1.5.7"
  DEPLOYMENT_SERVICE_ACCOUNT_NAME: "projects/${{ vars.PROJECT_ID }}/serviceAccounts/${{ secrets.IAC_SERVICE_ACCOUNT }}"
  DEPLOYMENT_LABELS: "owner=emes,email=m_dot_emes_at_f5_dot_com"
jobs:
  infra-manager:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_GIT_URL: "${{ github.server_url }}/${{ github.repository }}"
      DEPLOYMENT_GIT_SHA: "${{ github.sha }}"
      DEPLOYMENT_GIT_REF: "${{ github.head_ref || github.ref_name }}"
      DEPLOYMENT_GIT_SOURCE_DIRECTORY: foundations
      DEPLOYMENT_INPUTS_FILE: "${{ github.sha }}.tfvars"
    steps:
      - uses: actions/checkout@v6
      - uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
      - uses: google-github-actions/setup-gcloud@v3
      - name: Get PR details
        id: get_pr_details
        uses: actions/github-script@v8
        with:
          script: |
            return (
              await github.rest.repos.ListPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];
      - name: Get Infra Manager action steps
        id: get_im_action_steps
        uses: actions/github-script@v8
        with:
          script: |
            return {
              plan: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && (inputs.action || 'plan') == 'plan')
              apply: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (inputs.action || 'plan') == 'apply')
              delete: github.event_name == 'workflow_dispatch' && (inputs.action || 'plan') == 'delete',
              output: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && contains(fromJSON('["apply", "output"]'), (inputs.action || 'plan'))),
            };
      - uses: hashicorp/setup-terraform@v4
        if: ${{ fromJson(steps.get_im_action_steps.outputs.result).output }}
        with:
          terraform_version: "${{ env.DEPLOYMENT_TF_VERSION}}"
      - name: Install tfplandoc
        if: ${{ fromJson(steps.get_im_action_steps.outputs.result).plan }}
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: Azure/tfplandoc
          tag: v${{ env.TFPLANDOC_VERSION }}
      - name: Create local terraform variables file
        if: ${{ success() && (fromJson(steps.get_im_action_steps.outputs.result).plan ||fromJson(steps.get_im_action_steps.outputs.result).apply || fromJson(steps.get_im_action_steps.outputs.result).delete) }}
        # NOTE: This file defines the inputs for the Terraform executed by Infrastructure Manager. It mostly consists
        # of substitutions from root and job environment, but other values can be added too (e.g. labels), or can be
        # removed if not used (e.g. NGINX JWT secret identifier).
        run: |
          cat <<'EOF' > ${{ env.DEPLOYMENT_INPUTS_FILE }}
          # Autogenerated by ${{ github.workflow }} workflow
          project_id = "${{ vars.PROJECT_ID }}"
          name  = "${{ env.DEPLOYMENT_ID }}"
          repository = "${{ vars.OCI_REGISTRY }}"
          labels = {
            owner       = "emes"
            email       = "m_dot_emes_at_f5_dot_com"
          }
          allowlist_cidrs = ${{ vars.ALLOWLIST_CIDRS || '[]' }}
          dns = {
            base_domain = "${{ vars.DNS_BASE_DOMAIN }}"
            managed_zone_id = "${{ vars.DNS_MANAGED_ZONE_ID }}"
          }
          nginx_jwt_secret = {
            id = "${{ vars.NGINX_JWT_SECRET }}"
          }
          f5_ai_license_secret = {
            id = "${{ vars.F5_AI_LICENSE_SECRET }}"
          }
          EOF
      - name: Generate preview plan
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.result).plan }}
        run: ./.github/workflows/infra-manager-wrapper.sh plan
      - name: Generate markdown summary of plan for PR
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.result).plan }}
        run: |
          tfplandoc_v${{ env.TFPLANDOC_VERSION }} generate "${{ github.sha }}.json" > "${{ github.sha }}.plan.md"
      - name: Echo markdown plan summary to stdout if not associated with a PR
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.result).plan && !fromJson(steps.get_pr_details.outputs.result).number }}
        run: |
          cat "${{ github.sha }}.plan.md"
      - name: Add markdown output as comment on PR
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.result).plan && fromJson(steps.get_pr_details.outputs.result).number }}
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('${{ github.sha }}.plan.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: fromJson(steps.get_pr_details.outputs.result).number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Proposed Changes\n\nInfrastructure Manager will make the following changes on merge to main\n\n' + plan,
            })
      - name: Apply changes
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.result).apply }}
        run: ./.github/workflows/infra-manager-wrapper.sh apply
      - name: Generate a markdown output summary
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.result).output }}
        run: ./.github/workflows/infra-manager-wrapper.sh output
      - name: Echo output summary to stdout if not associated with a PR
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.result).output && !fromJson(steps.get_pr_details.outputs.result).number }}
        run: |
          cat "${{ github.sha }}.output.json"
      - name: Add markdown output as comment on PR
        if: ${{ success() && fromJson(steps.get_im_action_steps.outputs.result).output && fromJson(steps.get_pr_details.outputs.result).number }}
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('${{ github.sha }}.output.json', 'utf8');
            github.rest.issues.createComment({
              issue_number: fromJson(steps.get_pr_details.outputs.result).number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Output\n\nInfrastructure Manager has made change and this is the current output:\n\n```json\n' + output + '\n```\n',
            })
      - name: Delete deployment
        if: ${{ success() && (inputs.action || 'apply') == 'delete' }}
        run: ./.github/workflows/infra-manager-wrapper.sh delete
